-- Seoul(신) DB에 없던 13개 테이블 복구.
-- Mumbai(구) DB에는 52개 테이블이 있었으나 Seoul에는 39개뿐이었다.
-- 2026-07-26 전체 교체 마이그레이션이 Seoul 스키마를 기준으로 테이블을 열거하는 바람에
-- Mumbai에만 있던 아래 테이블들이 통째로 누락됐다.
--
-- 구조는 Mumbai PostgREST OpenAPI 정의에서 추출했고,
-- RLS 정책은 Seoul의 기존 테이블 관례(인증 필요 / 소속 식당 범위 / service_role 전체)를 따른다.
-- Mumbai에서 purchases·sales가 anon에게 전면 공개돼 있던 것은 의도치 않은 노출로 보아 인증 필요로 좁혔다.
-- 웹 어드민은 service_role로 조회하므로 이 제한에 영향받지 않는다.

-- ── 식당별 발주 가능 품목 ──────────────────────────────────────────────
-- 웹 회원 발주 페이지와 모바일 앱 발주 화면이 사용자 세션으로 직접 조회한다.
create table if not exists public.restaurant_products (
  id            uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  product_id    uuid not null references public.products(id) on delete cascade,
  display_order integer,
  created_at    timestamptz default now(),
  unique (restaurant_id, product_id)
);
create index if not exists restaurant_products_restaurant_id_idx
  on public.restaurant_products(restaurant_id);

alter table public.restaurant_products enable row level security;

create policy restaurant_products_member_read on public.restaurant_products
  for select using (
    restaurant_id in (
      select r.id from public.restaurants r
      join public.memberships m on m.organization_id = r.organization_id
      where m.user_id = auth.uid()
    )
  );

create policy restaurant_products_admin_read on public.restaurant_products
  for select using (
    auth.uid() in (
      select m.user_id from public.memberships m
      join public.organizations o on o.id = m.organization_id
      where o.organization_type = any (array['platform', 'operator'])
    )
  );

create policy restaurant_products_service_write on public.restaurant_products
  for all to service_role using (true) with check (true);

-- ── 푸시 토큰 ────────────────────────────────────────────────────────
-- 모바일 앱이 본인 토큰을 upsert(onConflict: user_id)한다.
create table if not exists public.push_tokens (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null unique,
  token      text not null,
  updated_at timestamptz default now()
);

alter table public.push_tokens enable row level security;

create policy push_tokens_own on public.push_tokens
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy push_tokens_service_write on public.push_tokens
  for all to service_role using (true) with check (true);

-- ── 푸시 예약 발송 ───────────────────────────────────────────────────
create table if not exists public.push_schedules (
  id           uuid primary key default gen_random_uuid(),
  slot         integer not null,
  send_time    text not null,
  title        text not null,
  body         text not null,
  is_active    boolean not null default true,
  created_at   timestamptz default now(),
  last_sent_at timestamptz
);

create table if not exists public.push_schedule_orgs (
  id              uuid primary key default gen_random_uuid(),
  schedule_id     uuid not null references public.push_schedules(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete cascade
);

alter table public.push_schedules enable row level security;
alter table public.push_schedule_orgs enable row level security;

create policy push_schedules_read on public.push_schedules
  for select using (auth.uid() is not null);
create policy push_schedules_service_write on public.push_schedules
  for all to service_role using (true) with check (true);

create policy push_schedule_orgs_read on public.push_schedule_orgs
  for select using (auth.uid() is not null);
create policy push_schedule_orgs_service_write on public.push_schedule_orgs
  for all to service_role using (true) with check (true);

-- ── 매입 ────────────────────────────────────────────────────────────
create table if not exists public.purchase_vendors (
  id         integer primary key generated by default as identity,
  name       text not null,
  created_at timestamptz default now()
);

create table if not exists public.purchases (
  id             integer primary key generated by default as identity,
  purchase_date  date not null,
  vendor_id      integer not null references public.purchase_vendors(id),
  product_name   text not null,
  quantity       numeric not null,
  unit           text,
  unit_price     integer not null,
  total_price    integer not null,
  payment_method text,
  is_paid        boolean default false,
  paid_date      date,
  notes          text,
  created_at     timestamptz default now()
);
create index if not exists purchases_purchase_date_idx on public.purchases(purchase_date);

-- ── 매출 ────────────────────────────────────────────────────────────
create table if not exists public.sales_vendors (
  id         integer primary key generated by default as identity,
  name       text not null,
  created_at timestamptz default now()
);

create table if not exists public.sales (
  id             integer primary key generated by default as identity,
  sale_date      date not null,
  vendor_id      integer not null references public.sales_vendors(id),
  product_name   text not null,
  quantity       numeric not null,
  unit           text,
  unit_price     integer not null,
  total_price    integer not null,
  payment_method text,
  is_paid        boolean default false,
  paid_date      date,
  notes          text,
  created_at     timestamptz default now()
);
create index if not exists sales_sale_date_idx on public.sales(sale_date);

alter table public.purchase_vendors enable row level security;
alter table public.purchases        enable row level security;
alter table public.sales_vendors    enable row level security;
alter table public.sales            enable row level security;

create policy purchase_vendors_read on public.purchase_vendors
  for select using (auth.uid() is not null);
create policy purchase_vendors_service_write on public.purchase_vendors
  for all to service_role using (true) with check (true);

create policy purchases_read on public.purchases
  for select using (auth.uid() is not null);
create policy purchases_service_write on public.purchases
  for all to service_role using (true) with check (true);

create policy sales_vendors_read on public.sales_vendors
  for select using (auth.uid() is not null);
create policy sales_vendors_service_write on public.sales_vendors
  for all to service_role using (true) with check (true);

create policy sales_read on public.sales
  for select using (auth.uid() is not null);
create policy sales_service_write on public.sales
  for all to service_role using (true) with check (true);

-- ── 광고 기획 ───────────────────────────────────────────────────────
create table if not exists public.ad_stores (
  id                   uuid primary key default gen_random_uuid(),
  organization_id      uuid references public.organizations(id) on delete set null,
  name                 text not null,
  brand_name           text,
  category             text not null,
  address              text,
  lat                  double precision,
  lng                  double precision,
  phone                text,
  signature_menu       text,
  certification_status text not null,
  ad_objectives        text[] not null default '{}',
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);

create table if not exists public.ad_store_products (
  id           uuid primary key default gen_random_uuid(),
  ad_store_id  uuid not null references public.ad_stores(id) on delete cascade,
  product_name text not null,
  product_id   uuid references public.products(id) on delete set null,
  created_at   timestamptz not null default now()
);

create table if not exists public.ad_trade_area_profiles (
  id                    uuid primary key default gen_random_uuid(),
  ad_store_id           uuid not null references public.ad_stores(id) on delete cascade,
  area_type             text,
  competition_level     text,
  competitor_count      integer,
  radius_m              integer,
  main_age_groups       text[] not null default '{}',
  peak_times            text[] not null default '{}',
  recommended_channels  text[] not null default '{}',
  recommended_angle     text,
  raw_api_json          jsonb,
  source                text not null,
  created_at            timestamptz not null default now()
);

create table if not exists public.ad_owner_pain_points (
  id                   uuid primary key default gen_random_uuid(),
  ad_store_id          uuid not null references public.ad_stores(id) on delete cascade,
  main_pain_point      text not null,
  sub_pain_points      text[] not null default '{}',
  ad_objective         text,
  weak_time_slot       text,
  strong_time_slot     text,
  selling_points       text[] not null default '{}',
  owner_notes          text,
  content_must_include text,
  content_do_not_use   text,
  created_at           timestamptz not null default now()
);

create table if not exists public.ad_content_briefs (
  id                    uuid primary key default gen_random_uuid(),
  ad_store_id           uuid not null references public.ad_stores(id) on delete cascade,
  trade_area_profile_id uuid references public.ad_trade_area_profiles(id) on delete set null,
  owner_pain_point_id   uuid references public.ad_owner_pain_points(id) on delete set null,
  key_message           text,
  target_customer       text,
  content_angle         text,
  recommended_channels  text[] not null default '{}',
  cta                   text,
  caution_notes         text,
  status                text not null,
  generated_by          text not null,
  model                 text,
  created_at            timestamptz not null default now()
);

alter table public.ad_stores              enable row level security;
alter table public.ad_store_products      enable row level security;
alter table public.ad_trade_area_profiles enable row level security;
alter table public.ad_owner_pain_points   enable row level security;
alter table public.ad_content_briefs      enable row level security;

create policy ad_stores_read on public.ad_stores
  for select using (auth.uid() is not null);
create policy ad_stores_service_write on public.ad_stores
  for all to service_role using (true) with check (true);

create policy ad_store_products_read on public.ad_store_products
  for select using (auth.uid() is not null);
create policy ad_store_products_service_write on public.ad_store_products
  for all to service_role using (true) with check (true);

create policy ad_trade_area_profiles_read on public.ad_trade_area_profiles
  for select using (auth.uid() is not null);
create policy ad_trade_area_profiles_service_write on public.ad_trade_area_profiles
  for all to service_role using (true) with check (true);

create policy ad_owner_pain_points_read on public.ad_owner_pain_points
  for select using (auth.uid() is not null);
create policy ad_owner_pain_points_service_write on public.ad_owner_pain_points
  for all to service_role using (true) with check (true);

create policy ad_content_briefs_read on public.ad_content_briefs
  for select using (auth.uid() is not null);
create policy ad_content_briefs_service_write on public.ad_content_briefs
  for all to service_role using (true) with check (true);
