-- 품목 분류 2단 전환 2/2 — 데이터 전환.
-- 새 분류를 아는 코드가 배포된 뒤에 돌린다(2026-09-17).
-- 대분류 9개 고정, 확장은 소분류로. 이름이 같은 품목(활성/비활성)은 함께 바뀐다.
with m(standard_name, cat, sub) as (values
  ('브로컬리','vegetable','엽채류'),
  ('깻잎','vegetable','엽채류'),
  ('꽃상추','vegetable','엽채류'),
  ('청상추','vegetable','엽채류'),
  ('양상추','vegetable','엽채류'),
  ('치커리','vegetable','엽채류'),
  ('쑥갓','vegetable','엽채류'),
  ('얼갈이','vegetable','엽채류'),
  ('열무','vegetable','엽채류'),
  ('배추','vegetable','엽채류'),
  ('알배기','vegetable','엽채류'),
  ('양배추','vegetable','엽채류'),
  ('적채','vegetable','엽채류'),
  ('청경채','vegetable','엽채류'),
  ('부추','vegetable','엽채류'),
  ('시금치','vegetable','엽채류'),
  ('어린잎 500g','vegetable','엽채류'),
  ('미나리','vegetable','엽채류'),
  ('당귀','vegetable','엽채류'),
  ('적근대','vegetable','엽채류'),
  ('궁채','vegetable','엽채류'),
  ('팽이버섯','vegetable','버섯류'),
  ('황소 팽이버섯','vegetable','버섯류'),
  ('느타리버섯','vegetable','버섯류'),
  ('새송이버섯','vegetable','버섯류'),
  ('목이버섯','vegetable','버섯류'),
  ('건목이버섯','vegetable','버섯류'),
  ('생목이버섯','vegetable','버섯류'),
  ('백목이버섯','vegetable','버섯류'),
  ('청양고추','vegetable','고추류'),
  ('청양고추B','vegetable','고추류'),
  ('홍고추','vegetable','고추류'),
  ('꽈리고추','vegetable','고추류'),
  ('배트남고추','vegetable','고추류'),
  ('무','vegetable','근채류'),
  ('당근','vegetable','근채류'),
  ('세척당근','vegetable','근채류'),
  ('감자 왕왕','vegetable','근채류'),
  ('감자 왕특','vegetable','근채류'),
  ('양파','vegetable','근채류'),
  ('양파(중)','vegetable','근채류'),
  ('깐양파','vegetable','근채류'),
  ('깐마늘(대)','vegetable','근채류'),
  ('깐마늘(주방)','vegetable','근채류'),
  ('마늘(소)','vegetable','근채류'),
  ('간마늘','vegetable','근채류'),
  ('깐생강','vegetable','근채류'),
  ('간생강','vegetable','근채류'),
  ('수입생강','vegetable','근채류'),
  ('청오이','vegetable','과채류'),
  ('백오이','vegetable','과채류'),
  ('주키니호박','vegetable','과채류'),
  ('애호박','vegetable','과채류'),
  ('인큐 호박','vegetable','과채류'),
  ('곱슬이','vegetable','콩나물·나물'),
  ('곱슬이(무료)','vegetable','콩나물·나물'),
  ('일자','vegetable','콩나물·나물'),
  ('매화 일자 콩나물','vegetable','콩나물·나물'),
  ('일자콩나물 10Kg','vegetable','콩나물·나물'),
  ('콩나물 10Kg','vegetable','콩나물·나물'),
  ('두절콩나물 8kg','vegetable','콩나물·나물'),
  ('숙주','vegetable','콩나물·나물'),
  ('재우 숙주','vegetable','콩나물·나물'),
  ('대파','vegetable','파류'),
  ('실파','vegetable','파류'),
  ('고수','vegetable','향채'),
  ('두부','vegetable','두부류'),
  ('연두부','vegetable','두부류'),
  ('대림유부','vegetable','두부류'),
  ('다진마늘','vegetable','절임·가공채소'),
  ('깍둑 단무지','vegetable','절임·가공채소'),
  ('김치 10kg','vegetable','절임·가공채소'),
  ('서진김치 10Kg','vegetable','절임·가공채소'),
  ('냉면무','vegetable','절임·가공채소'),
  ('레몬 6개 팩','fruit','과일'),
  ('바나나','fruit','과일'),
  ('사과','fruit','과일'),
  ('수박','fruit','과일'),
  ('참외','fruit','과일'),
  ('포도','fruit','과일'),
  ('계란','livestock','난류'),
  ('깐메추리알','livestock','난류'),
  ('스모크햄','livestock','육가공'),
  ('오양하이엠 비엔나 소세지','livestock','육가공'),
  ('무뼈닭발(국산)','livestock','정육'),
  ('눈꽃치즈','livestock','유제품'),
  ('모짜렐라','livestock','유제품'),
  ('김가루','seafood','해조류'),
  ('김가루 1Kg','seafood','해조류'),
  ('염장다시마','seafood','해조류'),
  ('마른다시마(국물용)','seafood','해조류'),
  ('쌈다시마 300g','seafood','해조류'),
  ('미역줄기','seafood','해조류'),
  ('오뎅','seafood','수산가공'),
  ('오양실속맛살','seafood','수산가공'),
  ('쌀','grain','쌀'),
  ('버드나무 쌀','grain','쌀'),
  ('함흥냉면','grain','면류'),
  ('면사랑 칡면사리','grain','면류'),
  ('라면사리','grain','면류'),
  ('신라면','grain','면류'),
  ('당면','grain','면류'),
  ('도토리묵 2Kg','grain','묵류'),
  ('도토리묵 6kg(판)','grain','묵류'),
  ('도토리묵채 5kg','grain','묵류'),
  ('다람쥐표 청포묵 2kg','grain','묵류'),
  ('떡볶이 3Kg','grain','분식'),
  ('해찬들 고추장','seasoning','장류'),
  ('해찬들 고추장 골드','seasoning','장류'),
  ('쌈장','seasoning','장류'),
  ('쌈장 말통','seasoning','장류'),
  ('삼화국간장 말통','seasoning','장류'),
  ('청정원불고기양념 10kg','seasoning','장류'),
  ('청정원 불고기양념 진 말통','seasoning','장류'),
  ('고향냉면비빔장','seasoning','장류'),
  ('미향 말통','seasoning','장류'),
  ('사과 2배식초 1.8l','seasoning','소스·식초'),
  ('화만식초 말통','seasoning','소스·식초'),
  ('빙초산','seasoning','소스·식초'),
  ('팬더굴소스 2kg(파우치)','seasoning','소스·식초'),
  ('업소용 와사비','seasoning','소스·식초'),
  ('솔표겨자','seasoning','소스·식초'),
  ('면사랑 냉면육수 소고기 5Kg','seasoning','소스·식초'),
  ('매실원액','seasoning','소스·식초'),
  ('오뚜기오''쉐프 순후추','seasoning','가루·분말'),
  ('통후추','seasoning','가루·분말'),
  ('산초가루','seasoning','가루·분말'),
  ('배트남고추가루','seasoning','가루·분말'),
  ('크러쉬드페퍼','seasoning','가루·분말'),
  ('튀김가루','seasoning','가루·분말'),
  ('미원','seasoning','가루·분말'),
  ('화미골드다시 2kg','seasoning','가루·분말'),
  ('백설 참기름 450ml(캔)','seasoning','기름'),
  ('해표 고추맛기름 1.8L','seasoning','기름'),
  ('식용류','seasoning','기름'),
  ('설탕 15kg','seasoning','당류'),
  ('설탕 3kg','seasoning','당류'),
  ('물엿 5Kg','seasoning','당류'),
  ('볶음참깨','seasoning','참깨'),
  ('통깨','seasoning','참깨'),
  ('2리터생수','misc','음료·커피'),
  ('자판기용 맥스웰 커피','misc','음료·커피'),
  ('하이퐁','misc','기타'),
  ('기타품목','misc','기타'),
  ('고무장갑 M','supply','위생장갑'),
  ('노랑고무장갑 M','supply','위생장갑'),
  ('니트릴장갑 S','supply','위생장갑'),
  ('목장갑','supply','위생장갑'),
  ('일회용 손장갑','supply','위생장갑'),
  ('업소용 냅킨','supply','종이·포장'),
  ('테이블냅킨','supply','종이·포장'),
  ('무지종이컵','supply','종이·포장'),
  ('쿠킹호일 30cm','supply','종이·포장'),
  ('롤팩 25cm','supply','종이·포장'),
  ('롤팩 30cm','supply','종이·포장'),
  ('비닐봉투','supply','종이·포장'),
  ('유한락스4리터','supply','청소·세척'),
  ('철수세미','supply','청소·세척'),
  ('행주','supply','청소·세척'),
  ('미니물티슈','supply','청소·세척'),
  ('라이터','supply','기타 소모품'),
  ('도깨비 방망이','supply','기타 소모품'),
  ('냉동다진마늘','frozen','냉동식품')
)
update products p set category = m.cat, subcategory = m.sub
from m where p.standard_name = m.standard_name;

-- 못 맞춘 품목은 기타식품으로 떨어뜨린다(화면에서 사라지지 않게)
update products set category = 'misc', subcategory = coalesce(subcategory, '기타')
where category in ('meat','dairy','etc') or category is null;

-- 이제 옛 값은 더 받지 않는다
alter table products drop constraint if exists products_category_check;
alter table products add constraint products_category_check check (category = any (array[
  'vegetable','fruit','livestock','seafood','grain','seasoning','frozen','misc','supply'
]));
